# EXPERIMENT 3: PYTHON DATA ANALYSIS (PANDAS)

## TOLENTINO, SHILOH R.

## 2ECE-A

## SEPTEMBER 15, 2026

In [14]:
import pandas as pd

cars = pd.read_csv('cars.csv')

### A. POSITIONAL AND LABEL-BASED SLICING

In [15]:
print("Shape of Data Frame:", cars.shape)
print("Column Names:",  cars.columns.tolist())
cars_6_to_10 = cars.iloc[5:10]
cars_6_to_10_subset = cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]
cars_6_to_10_subset

Shape of Data Frame: (32, 12)
Column Names: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

### B. MODEL LOOKUP

In [20]:
toyota = cars[cars['Model'] == 'Toyota Corolla']
toyota

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [21]:
pontiac = cars.loc[cars['Model'] == 'Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']]
pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### MULTI-MODEL SUBSETTING

In [18]:
models_to_extract = ['Datsun 710', 'Lotus Europa', 'Ferrari Dino']
columns_to_keep = ['Model', 'mpg', 'cyl', 'hp', 'gear']
selected_cars = cars.loc[cars['Model'].isin(models_to_extract), columns_to_keep]
display(selected_cars)
print("Shape of selected_cars:", selected_cars.shape)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape of selected_cars: (3, 5)